
let suggestions= [
    "Calzado",
    "Accesorios",
    "Quiénes Somos",
    "Artículos",
    "Ropa",
    "Contacto",
    "Pulsera",
    "Pulsera Pandora",
    "COllar",
    "Aretes",
    "Colibrí",
    "Acero Inoxidable",
    "Facebook",
    "Instagram",
    "Whatsapp",
    "Juego",
    "Juego de Collar y Aretes Colibrí",
    "Collar Tierra Madre",
    "Mod-1703",
    "Mod-1200",
    "Tenis",
    "Tenis All Star Plataforma",
    "Palatzo",
    "Palatzo Curvy",
    "Vestido",
    "Vestido V",
    "Falda",
    "Falda Mez",
];